### PR TITLE
Accept `list[str]` for `thermo_types` in `ThermoRester.search()`

### PR DESCRIPTION
**Pull request by janosh**
Let me know if I should add a test for this.

Also, I just used `str` in the type hint as using `Literal` would break single source of truth for accepted values. But happy to change that if you prefer `Literal`.

### CODE REVIEW

**Comment by janosh** [comment]
Am I causing [this error](https://github.com/materialsproject/api/actions/runs/3942975775/jobs/6747267239)?

```py
>           raise MPRestError(
                f"REST query returned with error status code {response.status_code} "
                f"on URL {response.url} with message:\n{message}"
            )
E           mp_api.client.core.client.MPRestError: REST query returned with error status code 504 on URL https://api.materialsproject.org/materials/?deprecated=False&crystal_system=Cubic&_all_fields=True&_limit=1 with message:
E           Server timed out trying to obtain data. Try again with a smaller request.
```

**Comment by munrojm** [comment]
Thank you for this @janosh, this looks great. The test failures aren't your fault. Something happened server-side so I am re-running. I'll merge once they all finish!

**Comment by janosh** [comment]
No problem. You prob know this but just in case not, you can enable [auto-merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) in the repo settings which will show a button below PRs to auto-merge as soon as CI passes.

**Comment by mattmcdermott** [comment]
Just wanna give a +1 on merging this. I would much rather be passing a string :)

**Comment by janosh** [comment]
@mattmcdermott You do get to see valid types [from the error msg](https://github.com/materialsproject/api/pull/729/files#diff-82e7fcd7874f159f0783219846112e653cccd14d1f78668e970b32759bf65305R113) if you pass an invalid one. But I think you're right, they should also be in the doc string.

**Pull request merged**
