### PR TITLE
Fixes the problem of weird synthesis search results when querying for a range 

### PR DESCRIPTION
**Pull request by hhaoyan**
Fixes the problem of weird synthesis search results when querying for a range. For example, when querying for 700-1000, the old code would return documents that only match one-sided criteria.

## Contributor Checklist

- [x] I have broken down my PR scope into the following TODO tasks
   -  [x] Use "$elemMatch" to for AND query of array elements.
- [x] I have run the tests locally and they passed.
- [x] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### CODE REVIEW

**Comment by hhaoyan** [comment]
Hi @munrojm I have added tests for the data adaptors. I was trying to add tests for the synthesis API data endpoint but confused because I don't know how to test an API that interacts with the database. Any ideas or could you point me to an existing test suite?

**Comment by munrojm** [comment]
Hi @hhaoyan, all you need to do is set an environment variable `MP_API_KEY` with the API key you obtain from https://next-gen.materialsproject.org, and `MP_API_ENDPOINT` with the appropriate endpoint. If you are running the app locally, this should be set to your localhost and appropriate port. Running pytest should then execute all of the tests.

You should also pull in changes from main which should let you do the above with any problems.

**Comment by hhaoyan** [comment]
Have added necessary tests. Should be good to go!

**Comment by munrojm** [comment]
Thanks @hhaoyan !

**Pull request merged**
