### PR TITLE
Enable caching for get_ion_reference_data

### PR DESCRIPTION
**Pull request by rkingsbury**
Cleanups for #428 to enable caching

### CODE REVIEW

**Comment by rkingsbury** [comment]
Not sure what happened with the commit history here. On my local machine it only shows 3 new commits compared to `main` (which is correct), but when I push it shows some redundant history that includes commits that were part of #428 . Sorry for the headache.

**Comment by rkingsbury** [comment]
I'm having trouble understanding why `@lru_cache` doesn't play well with mypy here. Adding to my confusion, the code here passes mypy linting on my machine but not in the CI. 

All unit tests also pass on my local machine, but in the CI there are several of these errors:
```
___________________ ERROR collecting tests/test_mprester.py ____________________
tests/test_mprester.py:9: in <module>
    from mp_api.matproj import MPRester
src/mp_api/__init__.py:6: in <module>
    from mp_api.client import MPRester
src/mp_api/client.py:39: in <module>
    class MPRester:
src/mp_api/client.py:582: in MPRester
    def _get_ion_reference_data(self, chemsys: tuple):
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/functools.py:490: in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
E   TypeError: Expected maxsize to be an integer or None
```

So basically I'm confused :) Can anyone advise?

**Comment by munrojm** [comment]
This appears to be an issue with Python 3.7x and not worth spending time fixing. For now, I would add `# type: ignore` to the end of lines 575 and 577.

Also, for consistency I would also vote to change your type hint references to the ones from the `typing` module. Namely, `dict` to `Dict` and `tuple` to `Tuple`.

**Comment by rkingsbury** [comment]
Thanks @munrojm . Linters pass now, and I updated the type hint refs per your suggestion.

**Comment by mkhorton** [comment]
Merging now, intend to make some further changes later.

**Pull request merged**
