### PR TITLE
Electrode document + changed to host url

### PR DESCRIPTION
**Pull request by jmmshn**
* Tested electrode endpoint
- Updated and validated the electrode endpoint
- Added functionality to query a subset of the periodic table with `BaseElement`

* Changed the format of the host URL
- Now accepts the full address with the database name like mp_core
   "mongodb+srv://xxxxxxx.net/mp_core"
- This was it will be easy to change the environment variable and test the API on a staging area before data is moved to production.  This change required a new version of Maggma

### CODE REVIEW

**Comment by jmmshn** [comment]
@munrojm Everything should work now with the data on Atlas

**Comment by jmmshn** [comment]
actually pymatgen needs to be bumped for this to work.
Is there any objection to pointing it to the master branch of pymatgen?

**Comment by mkhorton** [comment]
I can push an update to pymatgen, it's no problem

**Comment by munrojm** [comment]
This can be merged once a new environment variable for the `db_uri` has been made and updated through Patrick.

**Comment by jmmshn** [comment]
we can kill this right?

**Pull request closed without merging**
